### ISSUE TITLE
Event - The Game Awards 2019

### ISSUE THREAD

**Issue by aVitaliy** [quer/the-steam-awards#11]
Two Steam Emoticons in honor of The Game Awards 2019.

To receive, go to the page https://store.steampowered.com/sale/thegameawards
In the pop-up menu near the "Remind" button, check the "Notify by email" and "Notify on mobile device"

Question. Will you make a script to get these emoticons?

**Comment by quer** [comment]
alwas ;)

**Comment by quer** [comment]
i have made a version that shoud work just fine.

**Comment by aVitaliy** [comment]
It works fine if you uncomment the line. 

>     //getAuthwgtoken(RequestCommunity, function (authwgtoken) { // we doent need it.

Thank you for quickly resolving the issue.

**Comment by quer** [comment]
i have made a commit where i have removed that part :)
