### ISSUE TITLE
Steam Discovery Queue and Steamville Holiday Event

### ISSUE THREAD

**Issue by aVitaliy** [quer/the-steam-awards#12]
Hello!
Can you add Steam Discovery Queue to the script to receive 3 cards every day? 
https://store.steampowered.com/explore/

And is there a script to run Steamville Holiday Event?
https://store.steampowered.com/holidayquests

**Comment by quer** [comment]
The module “queue” is for the Discovery queue. Just ADD it 3 times and start it. 
Im Working on a module for the holiday, i did upload a “work in projeckt” of the module, but each Day a new quest is open so i jule have to have it done in time for the last quest

**Comment by aVitaliy** [comment]
> The module “queue” is for the Discovery queue. Just ADD it 3 times and start it.

Sorry. I just didn’t know about it.

**Comment by quer** [comment]
No problem, also did the Award 2019, where you get a card for each vote

**Comment by aVitaliy** [comment]
Hello!
You can add a time delay to the queue script. Because there was a problem when using the queue script - ban IP addresses or request to enter captcha. As a result, the script stops working. The browser does not open pages on the Steam website. After restarting the router and receiving a new IP address, everything works again. Apparently the script creates a lot of requests in a very small amount of time.

**Comment by quer** [comment]
Hey! i have added a delay to the queue module. but i have also create a new module "salequeue" that will ensure that each bot/account will get all 3 items that we get from the queue. it is not fully tested yet, but i thing it shoud work just fine.

**Comment by quer** [comment]
the module "salequeue" shoud work just fine, it will see if you get 3 new item after run queue 3 time. and if not it will run 3 more time to ensure it will get the item. if it stille do not get the item, it will tell you in the console. 
i have run'ed it and it works just fine. 

there is a bunch of     "setTimeout(..,{chance here});" where you can chance the time between each call, to ensure it doent lock you ip, whit to many calles to steam.
