### ISSUE TITLE
Error during connection try

### ISSUE THREAD

**Issue by githubshiel** [quer/the-steam-awards#13]
![scr1](https://user-images.githubusercontent.com/59182732/71384189-3f1d2c80-25e0-11ea-9785-dea235717986.JPG)
I dont know where to find "sharedSecret:" located in config.js
My account don't have 2FA auth. Only email code, so I left shred secret as empty.
![scr2](https://user-images.githubusercontent.com/59182732/71384423-73ddb380-25e1-11ea-920a-ebde8fad193c.JPG)
Can someone help?
Thanks in advance.

**Comment by quer** [comment]
Hey! it a thing whit node steam. but i think you can find what you need here:
https://github.com/seishun/node-steam/issues/344

**Comment by quer** [comment]
or maby: 
http://www.natewillard.com/blog/node-steam/steam/steam-guard/javascript/node/2015/09/09/node-Steamguard/

where you need to 
```
steamUser.on('updateMachineAuth', function(sentry, callback) {
  console.log('writing to file sentry');
  fs.writeFileSync('sentry', sentry.bytes);
  callback({ sha_file: getSHA1(sentry.bytes) });
});
function getSHA1(bytes) {
  var shasum = crypto.createHash('sha1');
  shasum.end(bytes);
  return shasum.read();
}
```
and edit part of the code to this:
```
steamClient.on('connected', function() {
  steamUser.logOn({
    account_name: '[redacted]',
    password: '[redacted]',
    // un-comment this when providing secondary auth-code from email
    // auth_code: '[redacted]', 
    sha_sentryfile: getSHA1(fs.readFileSync('sentry'))
  });
});
```

it a bit hard to eksplain, but hope the like on to eksplains it.

**Comment by githubshiel** [comment]
Sorry Sir, I'm not dealing so good with coding :/
I have tried to change some code, like you wrote above, but without success.
Is there any other way to fix it?
