### ISSUE TITLE
I can't use the voting module v2

### ISSUE THREAD

**Issue by Magellano** [quer/the-steam-awards#14]
Hello.

I cannot use the voting module v2 without an api key for multiple accounts. Here is a screenshot of the errors
![errr](https://user-images.githubusercontent.com/16334358/100341020-15893400-2fed-11eb-9b6f-d6b1129cbeb6.PNG)

I used to use the first version of the module. It was a little easier there. In the second version, it is not entirely clear how to specify the appid I need

What am I doing wrong?

**Comment by quer** [comment]
you might find what you are looking for on the answer on https://github.com/quer/the-steam-awards/issues/15, if not just add a comment on this issue again.

**Comment by Magellano** [comment]
It worked, thanks!

In steamAwardNominateGame_v2, I cannot add certain games myself? Does the script do it randomly?

**Comment by quer** [comment]
1.  the code find games via the search dialog, like if the account did the search, then use that app. 
That happens in getUnUsedAppId.
what you can do is to add a case in the MakeNominations methode. then it will skip that Nominate in the auto Nominate script. then call vote for that id whit you own game id. 
if you what all to be somefing specifik, you can just use somefing like:
```js
vote("50", 730 , _requestStore, sessionID, function () {
    vote("51", 520 , _requestStore, sessionID, function () {
osv...
```
You just have to ensure that the id is valid for the Nomination section. ( that why it do the search )

2. from what i have teste, it random when steam see it as have played the game. as i som account whit over 3k houers in a game, and some of them, only have to open the game and som had to play it over 10 min.. the code run the game for a min, and then check if it have the badge if not, it will run the game agrin for 10 min, and so on.. until it have the badge

**Comment by quer** [comment]
Thanks for being active, and using the project :)

**Comment by Magellano** [comment]
Thanks for the help. I'll try to check how it works a little later.
Also thanks for your cool tools!
