### ISSUE TITLE
(enhancement) Run queue one time instead of three

### ISSUE THREAD

**Issue by SENPAY98K** [quer/the-steam-awards#19]
Hi, the new discovery gives only one card.
So its better to edit the script to run once for each account.

**Comment by quer** [comment]
Thank! i have change it! :)

**Comment by SENPAY98K** [comment]
code keeps repeating the process in case it missing somethin,
please revise this option because it just over use requests and posts
![image](https://user-images.githubusercontent.com/77079047/123330963-91713d80-d536-11eb-9ccd-e03e7fdeba52.png)

**Comment by quer** [comment]
if you just what it to run once. whit out the check, just run the module called. 
`modules.push(require('./modules/queue'));` ( if im not wrong )

**Comment by SENPAY98K** [comment]
Okay i will try it now.. and send feedback

**Comment by SENPAY98K** [comment]
nice it works good, btw dont know why there that app in /90 in queue.js

**Comment by quer** [comment]
the app 60 that is used, is there to make a post it a app page, as it have to posted to one. so i use the app 60. i can be all game apps. it do not matter.

**Comment by SENPAY98K** [comment]
Okay thanks for the help

**Comment by quer** [comment]
NP
