### ISSUE TITLE
SyntaxError: Unexpected token '<'

### ISSUE THREAD

**Issue by stickerx** [quer/the-steam-awards#20]

**Comment by stickerx** [comment]
![2021-06-27_200937](https://user-images.githubusercontent.com/41187653/123558016-a8f13600-d783-11eb-9b8a-d2e27872534f.jpg)

Where the probleme

**Comment by quer** [comment]
As the error start whit. `<!DOCTYPE html>` that means that is what steam return in the url requst, if steam have a bad day. 
as log as you have not chance any thing in the module. just try to rerun it. 

the url that it request, shoud return a json object. but it return the html for a page not found. only comes if the url if wrong, or steam is heavy loaded

**Comment by stickerx** [comment]
Thanks for the response

It was working fine before, but now every time I want to turn it on it shows the error

**Comment by quer** [comment]
Seeing the command you entered. are you sure that the login info is right. And that you have called `NPM install`. 
normal it will console log "Connected to Steam." where it tell that is will try to login to steam. But i cant tell why it shoud run the modules, if it did not login to steam. 
have you change the code in any way? beside line 13. 
Make sure you have the same code as the github Repositorie

**Comment by stickerx** [comment]
I do not change anything but  all other modules run very well


but when I change 

modules.push(require('./modules/events/salequeue'));

to

modules.push(require('./modules/queue'));

its work very well
