### ISSUE TITLE
[Request] a module to complete the pillar badge tasks

### ISSUE THREAD

**Issue by SENPAY98K** [quer/the-steam-awards#22]
Can you make a module to complete that pillar badge, not all tasks but at least the possible ones..
I know some of them are already have a module here, but make any of the red underlinded ?
Thanks :)
![127748779-639b5bfb-87a7-4dd7-9c82-ad9a16041d86](https://user-images.githubusercontent.com/77079047/127750523-710ffb5c-e89c-44f3-b440-eed12842ada6.png)

**Comment by quer** [comment]
Hey! that might not be a bad ideer. 
I can see that i allready have module for allmost all. the "view a broadcast" is the hardest one. as it is a stream thing. 

But i can see if i can make one module that will do as many i can do. i will look in to it, when i have the time for it.

**Comment by SENPAY98K** [comment]
> Hey! that might not be a bad ideer.
> I can see that i allready have module for allmost all. the "view a broadcast" is the hardest one. as it is a stream thing.
> 
> But i can see if i can make one module that will do as many i can do. i will look in to it, when i have the time for it.

Yeah that would be cool, even if you combile all other modules into one or add their activate lines in top of script..
Anyway anything you make will be helpfull :)

**Comment by TioTiago** [comment]
Maybe this script can help if you have few accounts: https://gist.github.com/Ne3tCode/7ac3dbf68707a7f262b1db83bdae97ae (idk if work yet)

**Comment by quer** [comment]
It is all good. 
By seeing that like, it shoud be easy, to port over to a module. 
i will do it when I have the time for it.

**Comment by SENPAY98K** [comment]
Nice, i will try to put in a module if i could manage to do it correctly i send it here.
Thanks for the help ❤️

**Comment by SENPAY98K** [comment]
> Maybe this script can help if you have few accounts: https://gist.github.com/Ne3tCode/7ac3dbf68707a7f262b1db83bdae97ae (I don't know if it's allowed to share other links here, if no sorry)

Thanks for the info, I had this previously
![Screenshot 2021-08-05 134104](https://user-images.githubusercontent.com/77079047/128430122-7c523e0e-38e4-48f1-a2e2-28750accdd10.png)
After applying it the script i got +7 tasks done
![image](https://user-images.githubusercontent.com/77079047/128430299-bf8fa2c7-a533-400f-b97b-a940a7540158.png)

**Comment by SENPAY98K** [comment]
@quer , could you add this as well ? 
I have done some of the tasks here, i can send you to implement it ?

**Comment by quer** [comment]
this is not as easy, as some need some specifig flow. 
The easy once:
 * Use the Store Discovery Queue
 * Add a game to your wishlist
 * Add a friend to your friends list
 * Play a game
 * Review a game
 * Post a screenshot ( not sure, but if it just a request, it shoud be easy. ) 
 * Post a video ( not sure, but if it just a request, it shoud be easy. ) 
 * Rate an item on the Workshop
 * Subscribe to an item in the Steam Workshop
 * Set an avatar on your Community profile
 * Set your real name on your Community profile
 * Set a profile background ( but only if it just a request, it shoud be easy. ) 
 * Join a group
 * Comment on a friend's profile
 * Rate up content in your Activity Feed
 * Post a status to your friends
 * Comment on a friend's screenshot
 * Craft a game badge
 * Feature a badge on your profile
 * Search the Steam Discussions ( but only if it just a request, it shoud be easy. ) 

Where the rest is a bit harder. But all the above, is easy to make a way to do. But hard to make commen, to all to use. 
like 
 * Play a game ( need to know what game the account own, a fix would be to add, a free game to play ) 
 * Review a game ( need to know what game the account own, a fix would be to add, a free game to play ) 
 * Subscribe to an item in the Steam Workshop ( not sure if you can Subscribe to a game you do not own )
 * Comment on a friend's profile ( what account shoud this be, as it have to be a friend. ) 
 * Rate up content in your Activity Feed ( get the feed, to know what it shoud vote up. )
 * Post a status to your friends ( what friend )
 * Post a status to your friends ( what friend )
 * Craft a game badge ( so how to ensure the account have cards? shoud bye )
 
i can create a config part in the module, where you set it up. but it will hard to ensure all that end up using it, have all the stuff. 
then i will end up, have to create it, way to general. 

So im not sure, i will put my efforts into it.
only if i find a way to make the script, easy to use, where more or less can run it, by only setting a few settings.

**Comment by SENPAY98K** [comment]
> this is not as easy, as some need some specifig flow. The easy once:
> 
> * Use the Store Discovery Queue
> * Add a game to your wishlist
> * Add a friend to your friends list
> * Play a game
> * Review a game
> * Post a screenshot ( not sure, but if it just a request, it shoud be easy. )
> * Post a video ( not sure, but if it just a request, it shoud be easy. )
> * Rate an item on the Workshop
> * Subscribe to an item in the Steam Workshop
> * Set an avatar on your Community profile
> * Set your real name on your Community profile
> * Set a profile background ( but only if it just a request, it shoud be easy. )
> * Join a group
> * Comment on a friend's profile
> * Rate up content in your Activity Feed
> * Post a status to your friends
> * Comment on a friend's screenshot
> * Craft a game badge
> * Feature a badge on your profile
> * Search the Steam Discussions ( but only if it just a request, it shoud be easy. )
> 
> Where the rest is a bit harder. But all the above, is easy to make a way to do. But hard to make commen, to all to use. like
> 
> * Play a game ( need to know what game the account own, a fix would be to add, a free game to play )
> * Review a game ( need to know what game the account own, a fix would be to add, a free game to play )
> * Subscribe to an item in the Steam Workshop ( not sure if you can Subscribe to a game you do not own )
> * Comment on a friend's profile ( what account shoud this be, as it have to be a friend. )
> * Rate up content in your Activity Feed ( get the feed, to know what it shoud vote up. )
> * Post a status to your friends ( what friend )
> * Post a status to your friends ( what friend )
> * Craft a game badge ( so how to ensure the account have cards? shoud bye )
> 
> i can create a config part in the module, where you set it up. but it will hard to ensure all that end up using it, have all the stuff. then i will end up, have to create it, way to general.
> 
> So im not sure, i will put my efforts into it. only if i find a way to make the script, easy to use, where more or less can run it, by only setting a few settings.

I agree with you, using a config for settings i highly recommended,
Also everybody is using/playing csgo even new accounts are made for it (95%),
Where there is a friend thing, it can be added in setting's config,
View broadcast and rateup content in activity feed are 2 requests i guess,
(i looked in this script for url request and https://gist.github.com/Ne3tCode/7ac3dbf68707a7f262b1db83bdae97ae)
