### ISSUE TITLE
[REQUEST] Sending comments on Sharedfiles from a .txt

### ISSUE THREAD

**Issue by SENPAY98K** [quer/the-steam-awards#23]
Hi,
I could not find any script for commenting on steam sharedfiles such as artworks, screenshots and guide from a .txt file.
Something that randomly choose a line from a txt file and send it in comments of a steam sharedfile. :smiley: 
Is it possible to make a module for it ? Thanks so much. :heart:

**Comment by quer** [comment]
did a guick look for commenting on a guide. For some reason, to add a comment, you must post to a url like: 
https://steamcommunity.com/comment/PublishedFile_Public/post/76561197990233572/923012519/
where the last is the guide id. and the second last is the steamID of the account that created the guide. whit is wierd. 

and from what i can tell, it there no easy way to get the owner of the guides steamid. 
eks see this guide:
https://steamcommunity.com/sharedfiles/filedetails/?id=923012519
here the owner id is '76561197990233572', be there is no consisting way to get the value. 

and the the request need to look like:
![image](https://user-images.githubusercontent.com/3252080/128003905-84ba9b8f-d5d9-4f67-beae-73aabff5228c.png)
and all that data is also store in the source code on the page. and there is not consisting  to get that also.


so i dont think i will create a module for it. at least not at the moment.

**Comment by quer** [comment]
you can allway create it your self, i have made a guide in the wiki, where i try to explain how it is done

**Comment by SENPAY98K** [comment]
you said there is no easy way to get owner id? i we can get manually and put it in a config for at the top of the file `var id = 76xxxx` + `var guideid = 92....`

I will try to follow you instruction to make the module, then i i will post it here for you to revise it when you have time.
Thanks so much

**Comment by SENPAY98K** [comment]
Please check this out and let me know if i made a problem

```
module.exports = function(steamClient, RequestCommunity, RequestStore, SessionID, options, callback){

	var text = fs.readFileSync('./quotes.txt').toString('utf-8');
	var ss = text.split('\n')
	
	var steamid= "76561197990233572";
	var shareFileID = 923012519;
	var url = "https://steamcommunity.com/comment/PublishedFile_Public/post/"+steamid+"/"+shareFileID+"/";
	
		RequestCommunity.post({
			url: url,
			form:{
				comment: ss,
				count: 10,
				sessionid: SessionID,
				feature2: -1
			}
		}, function (error, response, body) {
			console.log(body);
			var i = 0;
			++i;
			setTimeout(function () {
				callback();
			}, 500);
		});
});

**Comment by SENPAY98K** [comment]
I followed your guide and copied some of the modules, here's what i made so far:
```
module.exports = function(steamClient, RequestCommunity, RequestStore, SessionID, options, callback){

	var ss = "testing";
	var steamid= "76561198097242611";
	var shareFileID = 2385237451;
	var url = "https://steamcommunity.com/comment/PublishedFile_Public/post/"+steamid+"/"+shareFileID+"/";
	
		RequestCommunity.post({
			url: url,
			form:{
				comment: ss,
				count: 10,
				sessionid: SessionID,
				feature2: -1
			}
		}, function (error, response, body) {
			console.log(body);
			var i = 0;
			++i;
			setTimeout(function () {
				callback();
			}, 500);
		});
};
```
It worked fine but all accounts comments are the same as defined in `ss`

![image](https://user-images.githubusercontent.com/77079047/128057729-0c88dfea-4da6-4211-bcfe-18ede1669ced.png)

Is there anything to make each account use a line from a text file ?

**Comment by quer** [comment]
Nice to see, you followed the guide.


you can create a Variable outside the function. that will act like a static. as it do not get reset between each account. then you can just create a list, or import one. and then just increase the index for each account, like the module 
https://github.com/quer/the-steam-awards/blob/master/modules/profileComment.js
where each account will take the next index, and comment on a profile. 

you can make so it load from a file, or create array. 


When you call the callback, just add a timeout on it before you call it. like in module:
https://github.com/quer/the-steam-awards/blob/master/modules/guideVoteLikeShare.js

**Comment by SENPAY98K** [comment]
> Nice to see, you followed the guide.
> 
> you can create a Variable outside the function. that will act like a static. as it do not get reset between each account. then you can just create a list, or import one. and then just increase the index for each account, like the module
> https://github.com/quer/the-steam-awards/blob/master/modules/profileComment.js
> where each account will take the next index, and comment on a profile.
> 
> you can make so it load from a file, or create array.
> 
> When you call the callback, just add a timeout on it before you call it. like in module:
> https://github.com/quer/the-steam-awards/blob/master/modules/guideVoteLikeShare.js

Thats really advanced thing to do for someone with know nothing in js 🙃

**Comment by TioTiago** [comment]
You can try this:

`var list = [
    "Rep+",
    "Nice work",
    "pro :p",
    "god of level",
    "send me a friend request,lets play together",
];

var i = 0;
var steamid = "76561198097242611";
var shareFileID = 2385237451;
var url = "https://steamcommunity.com/comment/PublishedFile_Public/post/"+steamid+"/"+shareFileID+"/";

module.exports = function(steamClient,RequestCommunity,RequestStore,SessionID,options,callback){
	RequestCommunity.post({
		url: url,
		form:{comment: list[i],count: 10,sessionid: SessionID,feature2: -1}
	},function (error,response,body){
		console.log(body);
		++i;
		setTimeout(function(){
			callback();
		},500);
	});
};`

**Comment by quer** [comment]
okay, let me help you a bit. 
Use this code, 

```js
const fs = require('fs');
const dataFromFile = fs.readFileSync('./textFile.txt', {encoding:'utf8', flag:'r'});
var text = dataFromFile .split("\n"); // will make a array, whit each row from the file
var i = 0; // to store what index to take next
module.exports = function(steamClient, RequestCommunity, RequestStore, SessionID, options, callback){

	
	var steamid= "76561198097242611";
	var shareFileID = 2385237451;
	var url = "https://steamcommunity.com/comment/PublishedFile_Public/post/"+steamid+"/"+shareFileID+"/";
	
		RequestCommunity.post({
			url: url,
			form:{
				comment: text[i] ,
				count: 10,
				sessionid: SessionID,
				feature2: -1
			}
		}, function (error, response, body) {
			console.log(body);

			++i; // will make sure the next account use the next index
			setTimeout(function () {
				callback();
			}, 500);
		});
};
```

the only thing here, it will die, if there is more account then text line

**Comment by quer** [comment]
Thank to @TioTiago for the example, i have added that one to the list. 
https://github.com/quer/the-steam-awards/commit/d75466c3d0a068888c02c5ed8aefad43b1c6b1e7

**Comment by SENPAY98K** [comment]
Thanks a lot for the help, its work very smooth.
I just want to add that the line feed `\n` does not work

Example:

![image](https://user-images.githubusercontent.com/77079047/128087566-4aa9a2a7-392a-40f0-8389-290809de3844.png)

Should be look like this if it reads that line feed `\n`

![image](https://user-images.githubusercontent.com/77079047/128087529-cae45086-39b0-46ca-96d3-4f78a36ebd53.png)

**Comment by SENPAY98K** [comment]
Any idea about multilines comments ?

**Comment by TioTiago** [comment]
use this: https://github.com/quer/the-steam-awards/blob/master/modules/CommentGuide.js worked fine here, example:

var list = [
    `♥ l、 
    （ﾟ､ ｡ ７ ♥ 
    　l、 ~ヽ 
    　じしf_, )ノ`,
    "Have a nice week!",
    "Rep+",
    "Nice work",
];

![image](https://user-images.githubusercontent.com/20051311/128296936-191f6d18-4a72-4018-9910-e566d32cee99.png)

**Comment by SENPAY98K** [comment]
> use this: https://github.com/quer/the-steam-awards/blob/master/modules/CommentGuide.js worked fine here, example:
> 
> ```js
> var list = [
>     `♥ l、 
>     （ﾟ､ ｡ ７ ♥ 
>     　l、 ~ヽ 
>     　じしf_, )ノ`,
>     "Have a nice week!",
>     "Rep+",
>     "Nice work",
> ];
> ```
> 
> ![image](https://user-images.githubusercontent.com/20051311/128296936-191f6d18-4a72-4018-9910-e566d32cee99.png)

I would like to, but i have made a lot of  different ascii quotes in .txt files
It really help me managing comments correctly..
Anyway i will try adding 
```
var list = [ `

];
```
in the .txt file and see

**Comment by quer** [comment]
maby this can help https://www.tutorialsteacher.com/javascript/javascript-eval

**Comment by SENPAY98K** [comment]
Did not work for me (i could not set idk), so i referd back the list in same module using `\n` to for multilines.. guess what? it worked.
Now i will just create many of the module with names of my comments packs and paste them inside each one.
Thanks a lot guys for the help
