### ISSUE TITLE
[REQUEST] Sharedfiles view counting

### ISSUE THREAD

**Issue by SENPAY98K** [quer/the-steam-awards#24]
Hi,
There is a module called "likeImage" and "guideVoteLikeShare".. does voting for steam sharedfiles but does count the views, you get likes and favorites but under author stats there is "Unique Visitors" which is not updating the number at all.
For example: a guide boosted by 120 accounts get 120 likes and 120 favorites and unique visitors stays 1

**Comment by quer** [comment]
Hey, that is true. Cant remember why i did not add it to the module, but i have now:
https://github.com/quer/the-steam-awards/commit/fe5e5a94ac86d30a0c668ace4adea4d06ec1c19a

**Comment by SENPAY98K** [comment]
Woah there was really quick, i will try it now thanks a lot.

**Comment by SENPAY98K** [comment]
Works like a charm thanks man

**Comment by SENPAY98K** [comment]
Woah there was really quick. Works like a charm thanks man.
