### ISSUE TITLE
SyntaxError: Unexpected identifier API key

### ISSUE THREAD

**Issue by stickerx** [quer/the-steam-awards#26]
I placed API key for each account in config.js

![143467300-b549109c-b412-4002-8bff-984b4ab7c1f5](https://user-images.githubusercontent.com/41187653/143474974-b1d737f7-5705-4b24-98e0-8884d35895a2.jpg)

**Comment by quer** [comment]
i think you did not read the last part of my comment on
https://github.com/quer/the-steam-awards/discussions/17

Where you need to remeber to add the "," at the end of the line above it.

**Comment by stickerx** [comment]
![2021-11-25_180536](https://user-images.githubusercontent.com/41187653/143480603-6bdf6a59-9650-4e53-a9a6-2304a6fe3896.jpg)

`var options = {
					Index: index,
					UserName: auth.steam_user,
					steamUser: steamUser,
					steamFriends: steamFriends,
					accountPretty: steamClient.steamID + " - " + auth.steam_user + ":",
 					ApiKey: auth.apiKey","`

**Comment by quer** [comment]
remove `","`

**Comment by stickerx** [comment]
where should add the ","

**Comment by quer** [comment]
in the call stack on the image you send, you can see it die's in "config.js"

where you line "apikey" need the , on the line above. 

```js
config.push({
	steam_user: "**",
	steam_pass: "**",
	sharedSecret: "**",
        apiKey: "**"
});
```
above is how it shoud be, see the `,` at the end of the sharedSecret line
