### ISSUE TITLE
(node:4444) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'sort' of undefined

### ISSUE THREAD

**Issue by aVitaliy** [quer/the-steam-awards#27]
I'm having a problem with steamAwardNominateGame_v2.js

![image](https://user-images.githubusercontent.com/32162150/143572592-28b10078-808c-46e6-a007-c3cc66311ba3.png)

**Comment by quer** [comment]
the happen on `json.response.games.sort(function(a, b){return b.playtime_forever - a.playtime_forever});`

that can only fail, if the accound do not have any games. Or if the account is not public. so the global apikey, do not have access to the games that on that account.

if you have the api key, foreach account you can add it to the config, and add so it use the fetch for each account, and not the top apikey. read more here 
https://github.com/quer/the-steam-awards/discussions/17#discussioncomment-305665

**Comment by aVitaliy** [comment]
I set all flags to public and then everything worked perfectly.
