### ISSUE TITLE
help with this module

### ISSUE THREAD

**Issue by stickerx** [quer/the-steam-awards#33]
Hello,  ;)

 I test this but I got this error

modules.push(require('./modules/joinGroup'));

```
var list = [
    "https://steamcommunity.com/groups/NewSteamCommunityBeta",
    "https://steamcommunity.com/groups/Infinity-CS-GO",
    "https://steamcommunity.com/groups/bigpicture"
    ANd so on..ANd.
]
var RequestCommunity;
var SessionID;
module.exports = async function(steamClient, _RequestCommunity, RequestStore, _SessionID, options, callback){
    RequestCommunity = _RequestCommunity;
    SessionID = _SessionID;
    for (let i = 0; i < list.length; i++) {
        const groupUrl = list[i];
        await JoinGroup(groupUrl)
    }
    callback()
}

function JoinGroup(groupUrl) {
    return new Promise(function (resolve) {
        RequestCommunity.post({
            url: groupUrl,
            form:{
                sessionID: SessionID,
                action: "join"
            }
        }, function (error, response, body) {
            setTimeout(function () {
                resolve();
            }, 500);
        });
    })
}
```

error

![2021-12-03_195715](https://user-images.githubusercontent.com/41187653/144657826-01f42255-b2a4-4c32-8682-d18935747967.jpg)

**Comment by quer** [comment]
you have change the main.js, to work whit the last event, that part, have messed up the code.

**Comment by quer** [comment]
you did this, if im am not wrong.
https://github.com/quer/the-steam-awards/issues/28#issuecomment-983757342

**Comment by stickerx** [comment]
I delete old main.js and downloaded new main.js 

i got this new error

![2021-12-06_120046](https://user-images.githubusercontent.com/41187653/144835011-a0ce35a9-87c5-4d53-b08c-eb71c6c424e5.jpg)

**Comment by quer** [comment]
I know that you are not good at coding. but you have to look at some code to be able to use the modules. As that module need to know what group you want to join. 

```js
var list = [
    "https://steamcommunity.com/groups/NewSteamCommunityBeta",
    "https://steamcommunity.com/groups/Infinity-CS-GO",
    "https://steamcommunity.com/groups/bigpicture"
    ANd so on..ANd.
]
```
That is the list, here you what to join 
`"https://steamcommunity.com/groups/NewSteamCommunityBeta",`
`"https://steamcommunity.com/groups/Infinity-CS-GO",`
`"https://steamcommunity.com/groups/bigpicture",`
whit is real links for the groups, 

but 
`ANd so on..ANd.` is not a group link, And as the text says, "and so on" as you have to enter your own groups..

**Comment by stickerx** [comment]
I am not good at coding   :(

As you said it

but Thank you, bro
