### ISSUE TITLE
21 vulnerabilities (11 moderate, 6 high, 4 critical)

### ISSUE THREAD

**Issue by idimo** [quer/the-steam-awards#41]
What am I doing wrong?

node js 16.13.2 is installed in the system

![image](https://user-images.githubusercontent.com/75911190/151559478-f78da07c-0a09-4ef1-9872-d20c6f3aefd8.png)

**Comment by quer** [comment]
all shoud be as expected. 
 you just have som setting to show warnings.  

what happens when you use the project ?

**Comment by quer** [comment]
A fast local fix, is to run `npm audit fix` and then remove the folder `node_modules` and file `package-lock.json` and then run `npm install` and then `npm audit fix`

Then there shoud only be one high think left. But by doing this, i **cant** ensure all work as it shoud. Will look into it. 
The one that i have that is still not fixed is: 
```
csv-parse  <4.4.6
Severity: high
Regular Expression Denial of Service in csv-parse - https://github.com/advisories/GHSA-582f-p4pg-xc74
fix available via `npm audit fix`
node_modules/steam/node_modules/csv-parse

1 high severity vulnerability
```

**Comment by idimo** [comment]
did as you said

> A fast local fix, is to run `npm audit fix` and then remove the folder `node_modules` and file `package-lock.json` and then run `npm install` and then `npm audit fix`

the launch outputs this:

![image](https://user-images.githubusercontent.com/75911190/151614839-5813fd67-019a-4af2-84c8-561ed5d1761c.png)

maybe there is a way to run this script in docker?

**Comment by SENPAY98K** [comment]
Don't audit fix, just delete everything then re-download the project again
run in `npm install` and ignore all those vulnerabilities... and you are good to go.

**Comment by quer** [comment]
i did have a small look, into the warnings. as the module `Steam` is archived. and will not have any other updates. i cant fix all the warning. if you use `npm audit fix` it will just not work. it will remove the warning. but then the npm steam module, will not work.
