### ISSUE TITLE
Connection to steam

### ISSUE THREAD

**Issue by EbadiDev** [quer/the-steam-awards#43]
Keep getting Connection Error
tried to use VPN but no luck
```
Connected to Steam.
Connection closed by server -  Error: Disconnected
    at SteamClient._disconnected (\the-steam-awards-master\node_modules\steam\lib\steam_client.js:186:24)
    at Connection.emit (node:events:527:28)
    at TCP.<anonymous> (node:net:709:12)
```

**Comment by quer** [comment]
have you also set up the `sharedSecret` for the account?

**Comment by EbadiDev** [comment]
Yes i did

**Comment by peteranh** [comment]
Sorry for hijacking this, but I'm also getting this error. However, I don't know what I need to set in sharedSecret. I couldn't find anything on wiki regarding it. Is it the 2-FA code from SteamGuard?

**Comment by quer** [comment]
@EbadiDev  the error is that the login informain is not valid. it dies right after it will try to login. so somefing is as it shoud be in the config.js file. 
Have you used any other js steam system before. so you know that the sharedSecret, is the right one. 

@peteranh the sharedSecret, is a code/key that is on the phone, that is used to generate the 2-fa key, that you normal login whit. if you only have the login way, where you get the 2-fa on a mail, look at issue https://github.com/quer/the-steam-awards/issues/44
