### ISSUE TITLE
logging problem

### ISSUE THREAD

**Issue by tailon222** [quer/the-steam-awards#44]
hi!. is there an option or anyway to logging without sharedSecret code?  i only use the email steam guard

**Comment by quer** [comment]
im just using the login, that Npm package `steam`, have created. 
And the login object from `main.js`, do have more options to add. 
see all here: 
https://github.com/SteamDatabase/Protobufs/blob/master/steam/steammessages_clientserver_login.proto
under the `CMsgClientLogon` sections.

and what i think you have to do. is a 2 flow. first start, whit only username and password. and then start whit username and password and add the propperty `auth_code` to the login object, whit the mail code. 
and then i shoud run. 

I have not testet whit a account whit `email steam guard`. but i know it is possible.
