### ISSUE TITLE
Doesn't work for account with only EMAIL STEAM AUTH ?

### ISSUE THREAD

**Issue by DoKnocK** [quer/the-steam-awards#46]
Doesn't work for account with only EMAIL STEAM AUTH ?

![image](https://user-images.githubusercontent.com/68970953/177401610-a20565b1-c4b1-44d4-a8bd-7a2467f3ed41.png)

![image](https://user-images.githubusercontent.com/68970953/177401365-5b8410ed-90df-42f5-ab4f-27622628f81d.png)

![image](https://user-images.githubusercontent.com/68970953/177401424-959e39db-8861-4e17-921a-b013fd9b62e5.png)

**Comment by quer** [comment]
Hey. 
the master branch, do not work whit email auth. 
but last week i releash in the [Upgrade-core](https://github.com/quer/the-steam-awards/tree/Upgrade-core
) branch. So you have to switch to that branch. to be able to do it. 

As i only have 2 account whit the mail auth, i have only tested whit thoes. and i did make it work. you have to follow the wiki page, to set it up. you can find it here:
https://github.com/quer/the-steam-awards/wiki/Setting-up#account-whit-mail-code

Please read the wiki. and give feed back on it, if it made sense or not.

**Comment by quer** [comment]
as there have not been any response to this issue, i will close it.

**Comment by DoKnocK** [comment]
Was away, will try the core branch you mentioned above, appreciate your prompt response @quer  :)
