### ISSUE TITLE
Cannot find module './modules/events/nextFest-oktober-2022'

### ISSUE THREAD

**Issue by idimo** [quer/the-steam-awards#50]
![image](https://user-images.githubusercontent.com/75911190/193819633-1209c92e-39f4-47ed-8cdc-e36cc2b7d81b.png)

**Comment by idimo** [comment]
![image](https://user-images.githubusercontent.com/75911190/193820812-39d9c8db-b2e8-4c66-a0d1-009eece7a97c.png)

**Comment by SENPAY98K** [comment]
i guess yoy moved the files ? or changed folder names !

**Comment by quer** [comment]
in the upgraded version, you doent need the `./modules/` As it will add it to it, later. 
so just use `events/nextFest-oktober-2022` and not `./modules/events/nextFest-oktober-2022`

let me know if it did not fix it.

**Comment by quer** [comment]
Np :)
