### ISSUE TITLE
nextFest-2022 not working

### ISSUE THREAD

**Issue by pontifezo** [quer/the-steam-awards#51]
Hello.
I tried to run module 'events/nextFest-2022', but nothing happened, account did not get the badge.

Console log:

>Connected to Steam.
>websession start
>1/2 running games : 30
>2/2 running games : 30
>Modules done

SummerSale3000_2022 module worked ok during past event, but nextFest-2022 not working for me now.

**Comment by quer** [comment]
you are running the work module, for the current, you have to run the `events/nextFest-oktober-2022` as it somefing else at this event.

**Comment by pontifezo** [comment]
Sorry, found my mistake, I downloaded master branch, not the Upgrade-core branch (where the 'nextFest-oktober-2022.js' is located).
