### ISSUE TITLE
HELP https://prnt.sc/a6esfxCmeboG

### ISSUE THREAD

**Issue by Aoshiin** [quer/the-steam-awards#66]
npm.psl : The term 'npm.psl' is not recognized as the name of a cmdlet, function, script file, or operable program. Che
ck the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ npm.psl
+ ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (npm.psl:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by Aoshiin** [comment]
and https://prnt.sc/Bt0PwU_Figt0

**Comment by quer** [comment]
i do not know this error directly. But i do belive it happen as you are using the Powerchell in a strikt mode. Just google the term, from the image, and there shoud be a guide, to open it whitout the strick mode.

**Comment by Aoshiin** [comment]
https://prnt.sc/l3kYXNIwfEcf error

**Comment by Aoshiin** [comment]
help https://prnt.sc/XTVgWqY3TehF

**Comment by quer** [comment]
> https://prnt.sc/l3kYXNIwfEcf error

The powerchell is not allow to create file on the path. 



> help https://prnt.sc/XTVgWqY3TehF

read more on https://github.com/quer/the-steam-awards/wiki/Setting-up#account-whit-mail-code
