### ISSUE TITLE
salequeue

### ISSUE THREAD

**Issue by idimo** [quer/the-steam-awards#67]
![image](https://github.com/quer/the-steam-awards/assets/75911190/139b1b8a-34cd-4826-a2d9-e5cdc7a4b75d)

soo how that fix?

**Comment by quer** [comment]
im on it. steam change the Notification informaion. so the old way, doent work. You can just run the module `queue` until i have a fix for it

**Comment by quer** [comment]
just update the module. it have been fixed.
