### ISSUE TITLE
steamawards 2024?

### ISSUE THREAD

**Issue by idimo** [quer/the-steam-awards#81]
Hi, will there be an update for steamawards2024?

**Comment by quer** [comment]
i will update the script tomorrow, if it doent work. I will run it for my account to see.

**Comment by idimo** [comment]
ty

**Comment by quer** [comment]
It should be live now. Thank for still showing instress in the project. will i be alble to get a comment on, it if work as expected. as it do work for me.

**Comment by idimo** [comment]
everything is working great, thank you, you are the best as always
