### ISSUE TITLE
MultiAccount

### ISSUE THREAD

**Issue by MrLoftyFTW** [quer/the-steam-awards#9]
Hi, I dont understend how to setup main.js for multiaccount
Can you help me pls?
Best regards

**Comment by quer** [comment]
All you have to do, is open file `config.js`, and add all the steam account informaitons. And then in the `main.js` you only have toi chance line 12 where it says `modules.push(require('./modules/guideVoteLikeShare'));` here you enter the file name of the module you what to be run.
